# Generated by Django 6.0 on 2025-12-04 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Material')),
                ('descripcion', models.TextField(verbose_name='Breve Explicación')),
                ('materia', models.CharField(choices=[('probabilidad', 'Probabilidad y Estadística'), ('calculo', 'Cálculo'), ('ecuaciones', 'Ecuaciones Diferenciales'), ('optimizacion', 'Optimización'), ('algebra', 'Álgebra Lineal'), ('metodos', 'Métodos Numéricos'), ('procesos', 'Procesos Estocásticos'), ('geometria', 'Geometría'), ('coloquios', 'Coloquios'), ('seminarios', 'Seminarios')], max_length=50, verbose_name='Asignatura')),
                ('tipo', models.CharField(choices=[('definicion', 'Definición/Teorema'), ('video', 'Video'), ('notebook', 'Notebook (.ipynb)'), ('aplicacion', 'Aplicación/Streamlit'), ('pdf', 'Archivo PDF'), ('url', 'Página de Interés/URL Externa')], max_length=50, verbose_name='Tipo de Recurso')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Archivo PDF')),
                ('archivo_notebook', models.FileField(blank=True, null=True, upload_to='notebooks/', verbose_name='Notebook Jupyter')),
                ('link_video', models.URLField(blank=True, null=True, verbose_name='Link de Video (YouTube/Vimeo)')),
                ('link_externo', models.URLField(blank=True, null=True, verbose_name='Link Externo (Para pág. interés)')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor/Autor')),
            ],
            options={
                'verbose_name': 'Material Didáctico',
                'verbose_name_plural': 'Materiales Didácticos',
            },
        ),
    ]
