# Generated by Django 6.0 on 2025-12-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contenido_archivo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen o Diagrama'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ponente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Ponente'),
        ),
    ]
